version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'

volumes:
  postgres:
