development: &defaults
  adapter: postgresql
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@postgres/currency_exchange_development' %>
  pool: 4
  reconnect: true
  reaping_frequency: 10
  password: postgres

test:
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@postgres/currency_exchange_test' %>

production:
  <<: *defaults
  database: currency_exchange_production
